### ISSUE TITLE
Summaries doesn't appear when you load new post on feed

### ISSUE THREAD

**Issue by tolgaaaltas** [imorland/synopsis#1]
Hi Ian, 
First of all, thank your for your awesome work, but there is one small bug in this extension. When i press load more button on main feed, new contents loads without summaries. You can check this bug at [FlarumTR](https://flarum.tr).

Best regards and have a healthy day.

**Comment by imorland** [comment]
Hi @tolgaaaltas thank you for letting me know about this, I'll look into the problem

**Comment by imorland** [comment]
Fixed in `0.1.3`
