### ISSUE TITLE
When searching the forum, the summary is still displayed in the first 100 characters

### ISSUE THREAD

**Issue by aaro-n** [imorland/synopsis#12]
question:
After opening the extension and setting the summary to 100 characters, the home page displays 100 characters. When searching the forum, the displayed summary is still the set 100 characters. When the extension is closed, the search summary will display keywords.
see the problem
Search snippets only show the first 100 characters
desired result
Display search terms when searching
<img width="1132" alt="截屏2022-08-06 上午11 21 09" src="https://user-images.githubusercontent.com/45537680/183231938-3bf6d0d3-3c95-4829-a1ed-f22bd4fb2836.png">
<img width="1122" alt="截屏2022-08-06 上午11 25 30" src="https://user-images.githubusercontent.com/45537680/183231947-75404ffb-b1b1-4300-a99d-a55096817a2c.png">
<img width="1060" alt="截屏2022-08-06 上午11 29 36" src="https://user-images.githubusercontent.com/45537680/183231954-bea6e79c-ce6b-4269-a326-891b8ea59a35.png">

**Comment by imorland** [comment]
Fixed in `1.3.0`
