### ISSUE TITLE
"r.slug is not a function"while "last post" mode chosen

### ISSUE THREAD

**Issue by edgeinfinity1** [imorland/synopsis#15]
This issue happens whenever:

- flarum/mentions and ianm/synopsis enabled together
- A reply was made in the post
- "Last post"mode is selected in synopsis
- Click into the post and then the render crashed with "r.slug is not a function" on console.

The workaround is just switch to "First post".
Any idea whats going on please?

**Comment by imorland** [comment]
Are you able to provide any additional information here? Is this still an isssue? I don't seem to be able to replicate the problem

**Comment by edgeinfinity1** [comment]
Sorry for the late reply, here is my `php flarum info`:
root@forum:/www/wwwroot/192.168.5.132# php flarum info
Flarum core: 1.8.3
PHP version: 8.0.26
MySQL version: 5.7.42-log
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, sodium, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlwriter, zip, fileinfo, redis, exif, gmp, Zend OPcache
+----------------------------------------+---------+------------------------------------------+
| Flarum Extensions                      |         |                                          |
+----------------------------------------+---------+------------------------------------------+
| ID                                     | Version | Commit                                   |
+----------------------------------------+---------+------------------------------------------+
| flarum-suspend                         | v1.8.1  |                                          |
| flarum-tags                            | v1.8.0  |                                          |
| askvortsov-auto-moderator              | v0.1.3  |                                          |
| flarum-likes                           | v1.8.0  |                                          |
| flarum-bbcode                          | v1.8.0  |                                          |
| fof-upload                             | 1.4.2   | 09d7c18e6ab8fbed43490db9fd59c5371838e1b2 |
| flarum-sticky                          | v1.8.0  |                                          |
| flarum-nicknames                       | v1.8.0  |                                          |
| flarum-lock                            | v1.8.0  |                                          |
| flarum-flags                           | v1.8.0  |                                          |
| afrux-forum-widgets-core               | v0.1.7  |                                          |
| fof-pages                              | 1.0.7   |                                          |
| fof-user-directory                     | 1.3.2   |                                          |
| flarum-mentions                        | v1.8.2  |                                          |
| antoinefr-money                        | v1.3.1  |                                          |
| flarum-subscriptions                   | v1.8.0  |                                          |
| flarum-markdown                        | v1.8.0  |                                          |
| zerosonesfun-bbcode-audio              | 3.1.3   | 7747545af60c6ebc2e9a775258da9ba1bcefd3b7 |
| zequeen-acgembed-remastered            | v1.1.2  |                                          |
| v17development-user-badges             | v1.1.0  |                                          |
| v17development-seo                     | v1.8.0  | cbbe884d2c1e0c79e0b708a7a4d924c2fc08545f |
| the-turk-stickiest                     | 3.0.1   |                                          |
| sycho-profile-cover                    | v1.3.5  |                                          |
| subasteve-action-log                   | v0.1.5  |                                          |
| pipecraft-id-slug                      | v1.1.0  |                                          |
| nearata-embed-video                    | 3.3.2   |                                          |
| michaelbelgium-discussion-views        | v7.2.1  | f904f7a7c2ceeb81114985b65870745a8510e634 |
| kilowhat-audit-free                    | 1.7.0   |                                          |
| justoverclock-staff-members-widget     | 0.1.3   |                                          |
| justoverclock-guestengagement          | 1.0.3   |                                          |
| imeepo-daily-check-in                  | v1.1.0  |                                          |
| ianm-synopsis                          | 1.3.1   |                                          |
| ianm-syndication                       | 1.3.4   |                                          |
| fof-username-request                   | 1.2.3   |                                          |
| fof-user-bio                           | 1.3.0   |                                          |
| fof-terms                              | 1.2.1   |                                          |
| fof-split                              | 1.1.0   |                                          |
| fof-sitemap                            | 2.2.1   |                                          |
| fof-profile-image-crop                 | 1.1.6   |                                          |
| fof-prevent-necrobumping               | 1.1.1   |                                          |
| fof-polls                              | 1.4.2   |                                          |
| fof-nightmode                          | 1.5.3   |                                          |
| fof-merge-discussions                  | 1.4.1   |                                          |
| fof-links                              | 1.2.0   |                                          |
| fof-linguist                           | 1.1.1   |                                          |
| fof-impersonate                        | 1.1.1   |                                          |
| fof-html-errors                        | 1.1.1   |                                          |
| fof-drafts                             | 1.2.7   |                                          |
| fof-doorman                            | 1.1.3   |                                          |
| fof-best-answer                        | 1.3.2   |                                          |
| flarum-statistics                      | v1.8.0  |                                          |
| flarum-lang-english                    | v1.8.0  |                                          |
| flarum-lang-chinese-simplified         | v1.3.0  |                                          |
| ecnu-im-sticky-sidenav                 | v1.1.0  |                                          |
| dem13n-topic-starter-label             | 0.1.8   |                                          |
| darkle-fancybox                        | 1.1.2   |                                          |
| club-1-cross-references                | v1.1.1  |                                          |
| clarkwinkelmann-who-read               | 1.4.1   |                                          |
| clarkwinkelmann-scout                  | 0.3.5   | 4e1eecd18f687b3105c8dd3cc6ca5f8dc434729d |
| clarkwinkelmann-prominent-post-numbers | 1.0.0   |                                          |
| clarkwinkelmann-money-rewards          | 1.0.0   |                                          |
| clarkwinkelmann-mailing                | 1.1.0   |                                          |
| clarkwinkelmann-emojionearea           | 1.0.0   |                                          |
| blomstra-sort-order-toggle             | 0.2.0   | 4e3cf5919fa2af5e09594eefebfb4506d6c330dc |
| blomstra-realtime                      | 0.2.18  |                                          |
| askvortsov-rich-text                   | v2.1.7  |                                          |
| askvortsov-pwa                         | v3.2.1  |                                          |
| askvortsov-moderator-warnings          | v0.6.3  |                                          |
| askvortsov-markdown-tables             | v1.2.1  |                                          |
| askvortsov-categories                  | v3.0.9  |                                          |
| afrux-online-users-widget              | v0.1.6  | 092802cdd833d6d028b94f4177f9d46be9d8486c |
| afrux-news-widget                      | v0.1.1  |                                          |
| afrux-forum-stats-widget               | v0.1.1  |                                          |
| acpl-mobile-tab                        | 1.4.1   |                                          |
+----------------------------------------+---------+------------------------------------------+
Base URL: https://forum.monika.love
Installation path: /www/wwwroot/192.168.5.132
Queue driver: redis
Session driver: redis (Code override. Configured to file)
Scheduler status: Active
Mail driver: smtp
Debug mode: off

I'm not really sure what information is needed, or may that be enough?
My forum is now running, so I'm afraid I cannot switch to LastPost to try to replicate the problem.

**Comment by edgeinfinity1** [comment]
Sorry for bothering, I found that this is a problem related with [clarkwinkelmann](https://github.com/clarkwinkelmann)
/
[flarum-ext-prominent-post-numbers](https://github.com/clarkwinkelmann/flarum-ext-prominent-post-numbers), which they released a fix around a month ago.
