### ISSUE TITLE
Add option for using last post summary instead of first post

### ISSUE THREAD

**Issue by eddiewebb** [imorland/synopsis#4]
Currently plugin uses initial post text in card, I would like latest post text instead.

**Comment by imorland** [comment]
This is already possible. Go to the extension settings in `/admin` and select `Last Post`

![image](https://user-images.githubusercontent.com/16573496/118634020-ffa14280-b7c9-11eb-919d-2973caeaa1a5.png)

**Comment by eddiewebb** [comment]
lol, yep, Sorry @imorland , too early yet this was meant for another extension 😬
