### ISSUE TITLE
Use "sticky" or specific tag for featured cards.

### ISSUE THREAD

**Issue by eddiewebb** [imorland/synopsis#5]
Rather than just top X discussions being cards, I would like ability to say to "use this tag (i.e. featured) for featured cards" OR to have option to say "show sticky discussions first" and treat them as the featured cards

**Comment by imorland** [comment]
I'm not quite sure what you mean here.

This extension simply adds an except from either the first or last post contents to the discussion lists. `flarum/sticky` does similar for stickied discussions, which are shown first (to guests, and to registered users if they've not read the discussion)

**Comment by eddiewebb** [comment]
Sorry @imorland , too early yet this was meant for another extension 😬
